### ISSUE TITLE
The args.model seems not used to get responses.

### ISSUE THREAD

**Issue by yqy2001** [ShengranHu/ADAS#5]
Hello~ Thanks for the nice work!
It seems that the `model` is hard coded and does not take the args.model as its value. https://github.com/ShengranHu/ADAS/blob/03dd85b2aded8a390653ece1abb7ba7e64ae311c/_mmlu/search.py#L76

**Comment by ShengranHu** [comment]
Hello, thank you for your interest in our work!

It can indeed be a bit confusing. The args.model is actually intended to define the model that the meta-agent uses, not the model used for testing generated agents. We’ve hardcoded the latter as the default value because using args in default arguments can lead to unexpected behavior due to how Python handles default argument evaluation. While it’s possible to refine this with more careful settings, we might just keep the current workable solution.

Thanks again for your input!

**Comment by yqy2001** [comment]
Got it. Thank you for the response.
